---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-example
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-example
            image: registry.your.company.com/cronnn:0.1
            args:
            - /bin/sh
            - -c
            - 'curl -I -H "X-Bypass-Cache: true" https://gebrauchtwagen.autohaus24.de/ -v -s'
          restartPolicy: OnFailure